### ISSUE TITLE
What is the difference between single, double quotes strings and template strings?

### ISSUE THREAD

**Issue by odv** [js-mentorship/javascript#3]
```(javascript)
let name = 'Razvan';
let dog = "Husky";
let longPhrase = `My dog's owner is ${name}`;
```

**Comment by RazvanBugoi** [comment]
Singe and double quotes are serving the same purpose and there is no difference between them. They are also known as 'simple' quotes.

Backticks are known as 'extended functionality' quotes. These are used to embed variables and expressions into a string.

**Comment by odv** [comment]
@RazvanBugoi While you are right about backticks, there is a subtle difference between single and double quotes strings.

For instance, what happens if I want to have a quoted word in my string? Ex: He said he was "working".

Assign the string in the example above to a variable and test what happens when you use double quotes then repeat and use single quotes.

You can either use the browser console or a site like https://jsbin.com/?console,output

**Comment by RazvanBugoi** [comment]
It looks like if you want to use quote inside the string, you have to use different type of quotes that the ones used for the string itself. 

For the example above we can have : 

let proposition = ' He said he was "working" '; // code will run as expected 
let proposition = ' He said he was 'working' '; // code won't run because we used the same type of quote 2 times.

**Comment by odv** [comment]
@RazvanBugoi  Exactly! Well done!
