### ISSUE TITLE
Logical operators exercise

### ISSUE THREAD

**Issue by odv** [js-mentorship/javascript#4]
a)Following condition is:
```(javascript)
if (1 + 2 == 3 || 1 + 4 == 3 && 1 + 1 == 2)
```

1.True
2.False

b)Following condition is:
```(javascript)
if ((1 + 2 == 3 || 1 + 4 == 3) && 1 + 1 == 2)
```

1.True
2.False

c)Following condition is:
```(javascript)
if (true && false || true && false || true && false)
```

1.True
2.False

d)Following condition is:
```(javascript)
if (true && false || true && false || true && false || true)
```

1.True
2.False

e)Following condition is:
```(javascript)
if (true && (false || true) && (false || true))
```

1.True
2.False

**Comment by RazvanBugoi** [comment]
a) alert (1 + 2 == 3 || 1 + 4 == 3 && 1 + 1 == 2) // true because we have 3=3 and `or` is looking for a true value;

b) alert ((1 + 2 == 3 || 1 + 4 == 3) && 1 + 1 == 2) // true because what's inside the parantheses has the highest precedence and so it becomes : ` true && 1 + 1 == 2 ` and so we have a true && true scenario.

c) alert (true && false || true && false || true && false) // false because the precedence of `&&` is higher than `||` and so it becomes : false || false || false scenario.

d) alert (true && false || true && false || true && false || true) // true because it becomes : false || false || false || true and since `||` is only looking for a true value, answer is true.

e) alert (true && (false || true) && (false || true)) // true because it becomes : true && true && true

**Comment by odv** [comment]
@RazvanBugoi Well done!
